function [] = print_pattern_stat(all_patterns)
%PRINT_PATTERN_STAT Print some info about the patterns
    fprintf('Total patterns: %d\nPixels  1: %.2f%%\nPixels -1: %.2f%%\n', ...
        size(all_patterns, 1), ...
        100*sum(all_patterns(:) == 1 )/numel(all_patterns), ...
        100*sum(all_patterns(:) == -1)/numel(all_patterns));
end

